"""SQLite persistence via SQLAlchemy."""
from __future__ import annotations

from datetime import date, datetime

from sqlalchemy import Boolean, Column, Date, DateTime, Float, ForeignKey, Integer, JSON, String, UniqueConstraint, create_engine, text
from sqlalchemy.orm import DeclarativeBase, relationship, sessionmaker

from app.config import settings


class Base(DeclarativeBase):
    pass


class User(Base):
    """Registered user with virtual capital for paper trading."""
    __tablename__ = "users"

    id = Column(Integer, primary_key=True)
    email = Column(String(120), unique=True, index=True, nullable=False)
    name = Column(String(80), nullable=False)
    password_hash = Column(String(255), nullable=False)
    capital = Column(Float, nullable=False, default=500000.0)  # ₹5L default, ₹10L option
    is_guest = Column(Boolean, nullable=False, default=False)   # Guest users can't access paper trading
    created_at = Column(DateTime, default=datetime.utcnow)


class PickRow(Base):
    __tablename__ = "picks"

    id = Column(Integer, primary_key=True)
    date = Column(Date, index=True, nullable=False)
    symbol = Column(String(16), index=True, nullable=False)
    side = Column(String(8), nullable=False)
    entry = Column(Float, nullable=False)
    stop_loss = Column(Float, nullable=False)
    target1 = Column(Float, nullable=False)
    target2 = Column(Float, nullable=False)
    confidence = Column(Float, nullable=False, default=0.0)
    last_price = Column(Float, default=0.0)
    expiry_day = Column(Integer, default=0)
    status = Column(String(16), default="active")
    created_at = Column(DateTime, default=datetime.utcnow)

    explanation = relationship("PickExplanation", back_populates="pick", uselist=False, cascade="all, delete-orphan")


class PickExplanation(Base):
    __tablename__ = "pick_explanations"

    pick_id = Column(Integer, ForeignKey("picks.id", ondelete="CASCADE"), primary_key=True)
    payload = Column(JSON, nullable=False)
    pick = relationship("PickRow", back_populates="explanation")


class DailyLevel(Base):
    """Cached pre-market levels per symbol/day so the day's math is reproducible."""
    __tablename__ = "daily_levels"

    id = Column(Integer, primary_key=True)
    date = Column(Date, index=True, nullable=False)
    symbol = Column(String(16), index=True, nullable=False)
    pdh = Column(Float)
    pdl = Column(Float)
    pivot = Column(Float)
    r1 = Column(Float)
    r2 = Column(Float)
    s1 = Column(Float)
    s2 = Column(Float)
    atr = Column(Float)
    avg_volume_20 = Column(Float)
    or_high = Column(Float)
    or_low = Column(Float)
    created_at = Column(DateTime, default=datetime.utcnow)


class DayStatusRow(Base):
    __tablename__ = "day_status"

    id = Column(Integer, primary_key=True)
    date = Column(Date, unique=True, nullable=False)
    no_trade = Column(Integer, default=0)
    reason = Column(String(120))
    expiry_day = Column(Integer, default=0)
    picks_count = Column(Integer, default=0)
    created_at = Column(DateTime, default=datetime.utcnow)


class MfNavRow(Base):
    """Daily MF NAV snapshot from AMFI — accumulates history for risk metrics."""
    __tablename__ = "mf_nav_history"
    __table_args__ = (UniqueConstraint("scheme_code", "date", name="uq_mf_nav_code_date"),)

    id = Column(Integer, primary_key=True)
    scheme_code = Column(String(12), index=True, nullable=False)
    date = Column(Date, index=True, nullable=False)
    nav = Column(Float, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)


class PaperTradeSignal(Base):
    """Paper-trade signal log — tracks hypothetical P&L without real orders.

    Each row records a signal generated by a strategy, its entry/SL/target
    levels, and (once resolved) the outcome and P&L. This lets you measure
    edge before risking real money.
    """
    __tablename__ = "paper_trade_signals"

    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)
    date = Column(Date, index=True, nullable=False)
    symbol = Column(String(16), index=True, nullable=False)
    market = Column(String(8), index=True, default="nse")  # nse, us
    strategy = Column(String(16), index=True, nullable=False)  # vwap, bollinger, ppo, scalp, orb
    side = Column(String(8), nullable=False)                  # long, short
    entry = Column(Float, nullable=False)
    stop_loss = Column(Float, nullable=False)
    target = Column(Float, nullable=False)
    confidence = Column(Float, default=0.0)
    status = Column(String(16), default="open", index=True)    # open, hit_target, stopped_out, expired
    entry_time = Column(DateTime, nullable=True)
    exit_time = Column(DateTime, nullable=True)
    exit_price = Column(Float, nullable=True)
    pnl_pct = Column(Float, nullable=True)                    # percentage P&L
    explanation = Column(JSON, nullable=True)                 # full signal explanation
    created_at = Column(DateTime, default=datetime.utcnow)


class PriceAlert(Base):
    """User-defined price alert — triggers when a symbol crosses a threshold."""
    __tablename__ = "price_alerts"

    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    symbol = Column(String(16), index=True, nullable=False)
    condition = Column(String(16), nullable=False)  # above, below, cross_up, cross_down
    target_price = Column(Float, nullable=False)
    note = Column(String(200), nullable=True)
    status = Column(String(16), default="active", index=True)  # active, triggered, deleted
    created_at = Column(DateTime, default=datetime.utcnow)
    triggered_at = Column(DateTime, nullable=True)
    triggered_price = Column(Float, nullable=True)


class DailyDigest(Base):
    """Daily market digest — compiled summary emailed to users."""
    __tablename__ = "daily_digests"

    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)
    date = Column(Date, index=True, nullable=False)
    subject = Column(String(200), nullable=False)
    body_text = Column(JSON, nullable=False)  # structured digest data
    body_html = Column(String, nullable=True)  # rendered HTML
    emailed = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)


class NotificationChannel(Base):
    """User-configured notification channels (Telegram/Discord)."""
    __tablename__ = "notification_channels"

    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    channel_type = Column(String(16), nullable=False)  # telegram, discord
    config = Column(JSON, nullable=False)  # {bot_token, chat_id} or {webhook_url}
    enabled = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)


class BotDecision(Base):
    """One row per signal generated by the autonomous trading bot per scan cycle."""
    __tablename__ = "bot_decisions"

    id = Column(Integer, primary_key=True)
    scan_time = Column(DateTime, index=True, nullable=False)
    date = Column(Date, index=True, nullable=False)
    symbol = Column(String(16), index=True, nullable=False)
    market = Column(String(8), default="nse", index=True)
    strategy = Column(String(16), index=True, nullable=False)  # murphy, scalp, vwap, bollinger, ppo
    side = Column(String(8), nullable=False)  # long, short
    entry = Column(Float, nullable=False)
    stop_loss = Column(Float, nullable=False)
    target = Column(Float, nullable=False)
    confidence = Column(Float, default=0.0)
    risk_reward = Column(Float, default=0.0)
    composite_score = Column(Float, nullable=True)  # Murphy composite 0-100
    verdict = Column(String(16), nullable=True)  # Murphy verdict
    source = Column(String(8), default="bot")
    status = Column(String(16), default="open", index=True)  # open, hit_target, stopped_out, expired
    exit_price = Column(Float, nullable=True)
    exit_time = Column(DateTime, nullable=True)
    pnl_pct = Column(Float, nullable=True)
    explanation = Column(JSON, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)


class StrategyRanking(Base):
    """Daily snapshot of each strategy's performance — used to pick the best."""
    __tablename__ = "strategy_rankings"

    id = Column(Integer, primary_key=True)
    date = Column(Date, index=True, nullable=False)
    strategy = Column(String(16), index=True, nullable=False)
    total_signals = Column(Integer, default=0)
    resolved = Column(Integer, default=0)
    wins = Column(Integer, default=0)
    losses = Column(Integer, default=0)
    win_rate = Column(Float, default=0.0)
    avg_pnl_pct = Column(Float, default=0.0)
    total_pnl_pct = Column(Float, default=0.0)
    best_trade_pct = Column(Float, nullable=True)
    worst_trade_pct = Column(Float, nullable=True)
    sharpe_ratio = Column(Float, nullable=True)
    wfe_score = Column(Float, nullable=True)  # walk-forward efficiency
    wfe_verdict = Column(String(16), nullable=True)  # robust, moderate, fragile, overfit
    rank = Column(Integer, default=0)
    recommendation = Column(String(16), default="caution")  # recommended, caution, avoid
    created_at = Column(DateTime, default=datetime.utcnow)


class DailyRecommendation(Base):
    """The bot's single best pick for the day — lowest risk, best profit potential."""
    __tablename__ = "daily_recommendations"

    id = Column(Integer, primary_key=True)
    date = Column(Date, unique=True, index=True, nullable=False)
    symbol = Column(String(16), nullable=False)
    name = Column(String(120), nullable=True)
    strategy = Column(String(16), nullable=False)
    side = Column(String(8), nullable=False)
    entry = Column(Float, nullable=False)
    stop_loss = Column(Float, nullable=False)
    target = Column(Float, nullable=False)
    confidence = Column(Float, default=0.0)
    risk_reward = Column(Float, default=0.0)
    composite_score = Column(Float, nullable=True)
    explanation = Column(String(500), nullable=True)
    caveats = Column(JSON, nullable=True)
    alternatives = Column(JSON, nullable=True)  # top-5 runners-up
    created_at = Column(DateTime, default=datetime.utcnow)


class StrategyVerification(Base):
    """Daily snapshot of each strategy's rolling verification status.

    Tracks whether a strategy is 'proven' (enough trades over enough days
    with positive win rate + P&L), 'testing' (not enough data yet), or
    'unproven' (enough data but poor performance).
    """
    __tablename__ = "strategy_verification"

    id = Column(Integer, primary_key=True)
    date = Column(Date, index=True, nullable=False)
    strategy = Column(String(16), index=True, nullable=False)
    # Rolling stats (last N days)
    days_tracked = Column(Integer, default=0)
    total_trades = Column(Integer, default=0)
    resolved_trades = Column(Integer, default=0)
    wins = Column(Integer, default=0)
    losses = Column(Integer, default=0)
    win_rate = Column(Float, default=0.0)
    avg_pnl_pct = Column(Float, default=0.0)
    total_pnl_pct = Column(Float, default=0.0)
    profitable_days = Column(Integer, default=0)
    consistency_pct = Column(Float, default=0.0)
    # Backtest stats (supplementary — used when live trades insufficient)
    backtest_win_rate = Column(Float, nullable=True)
    backtest_avg_return = Column(Float, nullable=True)
    backtest_days = Column(Integer, nullable=True)
    # Verdict
    verdict = Column(String(20), default="testing")  # proven / testing / unproven
    proven_since = Column(Date, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    __table_args__ = (UniqueConstraint("date", "strategy", name="uq_verification_date_strategy"),)


engine = create_engine(settings.db_url, connect_args={"check_same_thread": False})
SessionLocal = sessionmaker(bind=engine, autoflush=False, autocommit=False)


def init_db() -> None:
    Base.metadata.create_all(engine)
    # Add user_id column to existing paper_trade_signals table if missing
    # (create_all doesn't alter existing tables).
    with engine.connect() as conn:
        try:
            conn.execute(text("ALTER TABLE paper_trade_signals ADD COLUMN user_id INTEGER"))
            conn.commit()
        except Exception:
            pass  # Column already exists
        try:
            conn.execute(text("ALTER TABLE users ADD COLUMN is_guest BOOLEAN DEFAULT 0"))
            conn.commit()
        except Exception:
            pass  # Column already exists
        try:
            conn.execute(text("ALTER TABLE paper_trade_signals ADD COLUMN market VARCHAR(8) DEFAULT 'nse'"))
            conn.commit()
        except Exception:
            pass  # Column already exists

    # Create bot system user if not exists.
    from sqlalchemy import select as _select
    with SessionLocal() as db:
        existing = db.execute(_select(User).where(User.email == "bot@system")).scalar_one_or_none()
        if not existing:
            db.add(User(
                email="bot@system",
                name="Trading Bot",
                password_hash="!",  # not a real password — bot bypasses auth
                capital=500000.0,
                is_guest=False,
            ))
            db.commit()


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
